server:
  port: ${SERVER_PORT:}
  ssl:
    enabled: ${SSL_ENABLED:false}
    key-store: keystore.p12
    key-store-password: ${SSL_KEYSTORE_PASSWORD:}
spring:
  application.name: album-tracker
  datasource:
    url: ${DATABASE_URL:jdbc:postgresql://localhost/album_tracker}
    username: ${DATABASE_USERNAME:album_tracker}
    password: ${DATABASE_PASSWORD:album_tracker}
  jpa.hibernate.ddl-auto: update
  jackson.default-property-inclusion: non_null
